### ISSUE TITLE
Bin files not published

### ISSUE THREAD

**Issue by soumak77** [personality-insights/sunburst-chart#10]
Files in the [bin directory](https://github.com/personality-insights/sunburst-chart/tree/master/bin) did not get updated with the latest release

**Comment by germanattanasio** [comment]
It should be fixed now.

**Comment by soumak77** [comment]
@germanattanasio could you publish a 1.0.2 with the bin files?  The bin files added are not part of the 1.0.1 release that gets synced via npm.

**Comment by germanattanasio** [comment]
I'm sorry I don't know where my head is :(

**Comment by germanattanasio** [comment]
done
