### ISSUE TITLE
Not working with v3 output

### ISSUE THREAD

**Issue by basdirkse** [personality-insights/sunburst-chart#11]
Unfortunately, the current implementation does not work with the output of the latest version (v3) of personality insights. Will this lib get support for the new version?

**Comment by germanattanasio** [comment]
Yes it will. I will try to get some time to work on this.

**Comment by basdirkse** [comment]
Thats great, thanks!

Bas Dirkse

**Comment by germanattanasio** [comment]
@vibhasinghal @aprilwebster @agustincasamayor ^^^

**Comment by jeanbmar** [comment]
I've made a fork to fix v3 compatibility at https://github.com/jeanbmar/sunburst-chart.  
I've made structural changes to fit my own use, but you can basically just reuse the convertData method from the PersonalitySunburstChart class to wrap v3 data.

Live example at https://rawgit.com/jeanbmar/sunburst-chart/master/examples/example.html.

**Comment by germanattanasio** [comment]
Thanks @jeanbmar! @aprilwebster is working on this, I will make sure she take a look at your work.

**Comment by soumak77** [comment]
@germanattanasio any updates as to when this might get addressed?  Hopefully #12 and #13 can be addressed at the same time?

**Comment by germanattanasio** [comment]
Hey, Happy 2017 @aprilwebster will be working on this.

**Comment by germanattanasio** [comment]
The library now supports v3.
