### ISSUE TITLE
Issue when integrating with webpack

### ISSUE THREAD

**Issue by soumak77** [personality-insights/sunburst-chart#12]
I'm attempting to integrate this library into a project using angular2 built with webpack and typescript (generated via [angular-cli](https://github.com/angular/angular-cli)).  I have successfully integrated the sunburst chart using the standalone version which adds `PersonalitySunburstChart` to the `window` object.  I want to take a more modular approach and not use the `window` object but I cannot get the library imported using webpack.

The following should work to include the library via webpack:
```import * as PersonalitySunburstChart from 'personality-sunburst-chart';```

**Comment by germanattanasio** [comment]
We are working on this as part of #11.

**Comment by germanattanasio** [comment]
@soumak77 try to use `lib/index.js`. I think you will still run into issues because the library expects d3 and jquery to be available

**Comment by soumak77** [comment]
@germanattanasio I removed the jquery dependency with https://github.com/personality-insights/sunburst-chart/issues/5, any reason the dependency was reintroduced?

**Comment by germanattanasio** [comment]
OMG! you are right. I looked at your PR and reintroduced the changes removing jquery. 
You should also be able to use DOM nodes and class selector like `.my-class`.

2.0.3 has the changes.
