### ISSUE TITLE
provide API accepting DOM element

### ISSUE THREAD

**Issue by soumak77** [personality-insights/sunburst-chart#13]
It would help to expose this library to accept a raw DOM element instead of just a string ID.  This would allow the library to be used multiple times on the same page, as well as provide better integration with modular driven UIs.

**Comment by germanattanasio** [comment]
Good idea, @aprilwebster can you take a look at this?

**Comment by germanattanasio** [comment]
@soumak77 can you check the latest version. I accepts a DOM node now.

**Comment by soumak77** [comment]
@germanattanasio this doesn't work due to the code expecting **selector** to be a string https://github.com/personality-insights/sunburst-chart/blob/master/src/index.js#L85

I would like to propose adding a new **element** option which accepts a DOM element.  I have this working locally.  I'll submit a PR with this change.
