### ISSUE TITLE
Remove branches through options object

### ISSUE THREAD

**Issue by arypbatista** [personality-insights/sunburst-chart#2]
Yeah, people will want to remove branches, specially the 'behavior' one. Let's add an options object to component's instantiation.

**Comment by soumak77** [comment]
@germanattanasio I've come across this requirement as well and wouldn't mind implementing it.  My proposed solution would add a `Options.exclude` property which is an array of ids to exclude from rendering.  The valid ids would be the same ones the library is [already checking for](https://github.com/personality-insights/sunburst-chart/blob/master/src/personality-chart-renderer.js#L323-L328), specifically:
- personality
- needs
- values
- sr
- sbh
- blank

Using this solution, I could exclude the social behavior from rendering in the sunburst chart if I passed the value `Options.exclude = ['sbh']`.

**Comment by germanattanasio** [comment]
I like it and it think it's not a breaking change if you just add `exclude`. I'm happy with a PR @soumak77.
