### ISSUE TITLE
Not rendering "Values" bar completely

### ISSUE THREAD

**Issue by vaibhav1792** [personality-insights/sunburst-chart#22]
Hi! Please have a look at the following output chart. It "Values" bar is being incompletely rendered. What could be the issue??

![sunchart](https://cloud.githubusercontent.com/assets/20255074/23713549/4fc208b6-044c-11e7-8621-0f210ba200e4.png)

**Comment by inakineitor** [comment]
What file and version are you using?

**Comment by vaibhav1792** [comment]
I am using v3. I have taken sample code from example_v3.html...

**Comment by inakineitor** [comment]
Could you please show me the code? May be I can find the problem.

**Comment by vaibhav1792** [comment]
I am getting JSON response using AJAX and then using following code:
```
var chart = new PersonalitySunburstChart({'selector': '#sunburstChart', 'version': 'v3'});
chart.show(profile, 'profile_photo.jpg');
```

And following are the dependencies:
```
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.17/d3.min.js"></script>
<script type="text/javascript" src="https://unpkg.com/personality-sunburst-chart@2.0.4/dist/index.js"></script>
<script src="https://d3js.org/d3-color.v1.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" crossorigin="anonymous">
```

I am using bootstrap 4 alpha instead of bootstrap 3. Could this be the issue??

**Comment by inakineitor** [comment]
The chart part of your code I am sure is correct. And your dependencies also seem to be; I tried your dependencies in my website code and it worked perfectly, so I don't think they are the problem.
I am not one of the developers of the library, so I don't know its inner working. It could be some other css you have. If that isn't the problem, I would contact one of the developers, @germanattanasio, @arypbatista and @aprilwebster.

**Comment by vaibhav1792** [comment]
What other CSS could cause the problem?? I am using simple grid layout with two columns, one of them containing sunburst chart. No fancy stuff. I even tried removing the grid layout altogether, still have the same issue.

**Comment by inakineitor** [comment]
If you don't have any other css, I don't know what would be the cause of the problem. I would contact the lead developers.

**Comment by germanattanasio** [comment]
Is this just happening to you or you found this to be a problem in the library? I want to make sure I can reproduce your problem. Can you share the code you are using?

**Comment by germanattanasio** [comment]
This issue has no reproducible steps. Please re-open this issue if it still occurs.
Check the CONTRIBUTING.md for an example.
