### ISSUE TITLE
publish 2.1.0 to npm 

### ISSUE THREAD

**Issue by soumak77** [personality-insights/sunburst-chart#25]
Version 2.1.0 isn't on npm: https://www.npmjs.com/package/personality-sunburst-chart

**Comment by germanattanasio** [comment]
I published 2.1.0 but it doesn't appear on npm. I tried doing another release but same problem.

See https://github.com/npm/npm/issues/12738

**Comment by soumak77** [comment]
@germanattanasio could you try publishing one more time to see if the issue is resolved?

**Comment by soumak77** [comment]
@germanattanasio I just ran `npm update` and it downloaded 2.1.2 so looks like all is good!
