### ISSUE TITLE
Add support for different locales

### ISSUE THREAD

**Issue by soumak77** [personality-insights/sunburst-chart#28]
I would like to be able to see the trait names in the visualization in languages other than english.  This should be fairly simple to integrate using https://github.com/personality-insights/trait-names.

**Comment by rustyoldrake** [comment]
hi @aprilwebster  - thanks for note in Slack
what's the level of effort here - i.e. the incremental effort on top of other PI work - to do this?

**Comment by aprilwebster** [comment]
@soumak77 thanks for adding this issue!  It's something we had been thinking about as a future localization update to the demo.  I'll try to get to it soon, but it isn't something we have prioritized in the next couple of sprints.  If you'd like to take a shot at it, that would be great!

**Comment by aprilwebster** [comment]
@rustyoldrake - I'll have a closer look and get back to you soon.

**Comment by germanattanasio** [comment]
@aprilwebster What's your estimate on this?

**Comment by soumak77** [comment]
This has been resolved in https://github.com/personality-insights/sunburst-chart/pull/31.  Sync the PR and use `npm start` to test the changes.  D3 version 4 support can easily be disabled if you want to publish the changes before getting D3 version 4 working.
