### ISSUE TITLE
remove jQuery dependency

### ISSUE THREAD

**Issue by soumak77** [personality-insights/sunburst-chart#5]
I looked through the source code and the dependency on jQuery is only needed for a two jQuery methods (`$` and `$.empty`).  I am trying to use this library with Angular and I don't want to be forced to include such a large dependency like jQuery.  Can those few methods be rewritten to use native code?

jQuery usage:
- https://github.com/personality-insights/sunburst-chart/blob/master/src/main.js#L54
- https://github.com/personality-insights/sunburst-chart/blob/master/src/main.js#L81
- https://github.com/personality-insights/sunburst-chart/blob/master/src/main.js#L162

**Comment by germanattanasio** [comment]
can you write a pull request for this?

**Comment by soumak77** [comment]
@germanattanasio sure
